package com.goit.dev10.configs;

public class ConnectionConfig {
    private ConnectionConfig() {
    }
    public static final int BATCH_SIZE = 30;
    public static final String URL_JDBC = "jdbc:postgresql://localhost:5432/shopdb";
    public static final String USER = "myuser";
    public static final String PASSWORD ="mysecretpassword";
    public static final String TABLE_NAME = "worker";
    public static final String CREATE_TABLE = "create table public."+TABLE_NAME+"\n" +
            "(\n" +
            "    worker_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
            "    name TEXT NOT NULL,\n" +
            "    birthday DATE,\n" +
            "    level TEXT NOT NULL,\n" +
            "    salary NUMERIC NOT NULL\n" +
            ");\n";

}
